<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.10" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="NUnit" Version="4.6.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Mocks\" />
    <Folder Include="IntegrationTests\" />
    <Folder Include="UnitTests\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Demo.Archivero.Application\Demo.Archivero.Application.csproj" />
    <ProjectReference Include="..\Demo.Archivero.Converter.Worker\Demo.Archivero.Converter.Worker.csproj" />
    <ProjectReference Include="..\Demo.Archivero.Infrastructure.ServiceBus\Demo.Archivero.Infrastructure.ServiceBus.csproj" />
    <ProjectReference Include="..\Demo.Archivero.Domain\Demo.Archivero.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="10.0.10" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <ProjectReference Include="../Demo.Archivero.Backend.Api/Demo.Archivero.Backend.Api.csproj" />
  </ItemGroup>
</Project>
